version: 2
updates:
  # shields.io dependencies
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: friday
      time: '12:00'
    open-pull-requests-limit: 99
    rebase-strategy: disabled
    ignore:
      # https://github.com/badges/shields/issues/7324
      # https://github.com/badges/shields/issues/7447
      # we're stuck with these versions until Safari is compatible with lookbehind regex syntax
      # https://caniuse.com/js-regexp-lookbehind
      - dependency-name: 'decamelize'
      - dependency-name: 'humanize-string'

      # https://github.com/badges/shields/pull/7288#issuecomment-974699240
      - dependency-name: '@types/node'

  # badge-maker package dependencies
  - package-ecosystem: npm
    directory: '/badge-maker'
    schedule:
      interval: weekly
      day: friday
      time: '12:00'
    open-pull-requests-limit: 99
    rebase-strategy: disabled

  # close-bot package dependencies
  - package-ecosystem: npm
    directory: '/.github/actions/close-bot'
    schedule:
      interval: weekly
      day: friday
      time: '12:00'
    open-pull-requests-limit: 99
    rebase-strategy: disabled

  # GH actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 99
    rebase-strategy: disabled
