public:
  bind:
    address: '::'

  metrics:
    prometheus:
      enabled: false
      endpointEnabled: false
    influx:
      enabled: false
      timeoutMilliseconds: 1000
      intervalSeconds: 15
  ssl:
    isSecure: false

  cors:
    allowedOrigin: []

  persistence:
    dir: './private'

  services:
    github:
      baseUri: 'https://api.github.com/'
      debug:
        enabled: false
        intervalSeconds: 200
    trace: false

  cacheHeaders:
    defaultCacheLengthSeconds: 120

  rateLimit: true

  handleInternalErrors: true

  fetchLimit: '10MB'

  shieldsProductionHerokuHacks: false

private: {}
