public:
  bind:
    address: '::'

  metrics:
    prometheus:
      enabled: false
    influx:
      uri: http://localhost:8081/telegraf
      timeoutMilliseconds: 1000
      intervalSeconds: 2000

  ssl:
    isSecure: false

  cors:
    allowedOrigin: []

  persistence:
    dir: './private'

  services:
    github:
      baseUri: 'https://api.github.com/'
      debug:
        enabled: false
        intervalSeconds: 200
    trace: false

  profiling:
    makeBadge: false

  cacheHeaders:
    defaultCacheLengthSeconds: 120

  rateLimit: true

  handleInternalErrors: true

  fetchLimit: '10MB'

private: {}
