private:
  # These are the keys which are set on the production servers.
  curseforge_api_key: ...
  discord_bot_token: ...
  gh_client_id: ...
  gh_client_secret: ...
  gitlab_token: ...
  reddit_client_id: ...
  reddit_client_secret: ...
  sentry_dsn: ...
  shields_secret: ...
  sl_insight_userUuid: ...
  sl_insight_apiToken: ...
  twitch_client_id: ...
  twitch_client_secret: ...
  weblate_api_key: ...
  wheelmap_token: ...
  youtube_api_key: ...
