# Copy this file to `config/local.yml` and fill it in! It will be gitignored.

private:
  # The possible values are documented in `doc/server-secrets.md`. Note that
  # you can also set these values through environment variables, which may be
  # preferable for self hosting.
  curseforge_api_key: '...'
  gh_token: '...'
  gitlab_token: '...'
  obs_user: '...'
  obs_pass: '...'
  reddit_client_id: '...'
  reddit_client_secret: '...'
  twitch_client_id: '...'
  twitch_client_secret: '...'
  weblate_api_key: '...'
  wheelmap_token: '...'
  youtube_api_key: '...'
