version: 1
update_configs:
  # shields.io dependencies
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    automerged_updates:
      - match:
          dependency_name: 'chai*'
          update_type: 'semver:minor'
      - match:
          dependency_name: 'cypress'
          update_type: 'semver:minor'
      - match:
          dependency_name: 'eslint*'
          update_type: 'semver:minor'
      - match:
          dependency_name: 'mocha*'
          update_type: 'semver:minor'
      - match:
          dependency_name: 'sazerac'
          update_type: 'semver:minor'
      - match:
          dependency_name: 'sinon*'
          update_type: 'semver:minor'
      - match:
          dependency_name: 'snap-shot-it'
          update_type: 'semver:minor'

  # badge-maker package dependencies
  - package_manager: 'javascript'
    directory: '/badge-maker'
    update_schedule: 'weekly'

  # approve-bot package dependencies
  - package_manager: 'javascript'
    directory: '.github/actions/approve-bot'
    update_schedule: 'weekly'
