name: Services
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches:
      - 'gh-readonly-queue/**'

jobs:
  test-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 22

      - name: Service tests (triggered from local branch)
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: ./.github/actions/service-tests
        with:
          github-token: '${{ secrets.GH_PAT }}'
          curseforge-api-key: '${{ secrets.SERVICETESTS_CURSEFORGE_API_KEY }}'
          librariesio-tokens: '${{ secrets.SERVICETESTS_LIBRARIESIO_TOKENS }}'
          obs-user: '${{ secrets.SERVICETESTS_OBS_USER }}'
          obs-pass: '${{ secrets.SERVICETESTS_OBS_PASS }}'
          pepy-key: '${{ secrets.SERVICETESTS_PEPY_KEY }}'
          reddit-client-id: '${{ secrets.SERVICETESTS_REDDIT_CLIENT_ID }}'
          reddit-client-secret: '${{ secrets.SERVICETESTS_REDDIT_CLIENT_SECRET }}'
          sl-insight-user-uuid: '${{ secrets.SERVICETESTS_SL_INSIGHT_USER_UUID }}'
          sl-insight-api-token: '${{ secrets.SERVICETESTS_SL_INSIGHT_API_TOKEN }}'
          twitch-client-id: '${{ secrets.SERVICETESTS_TWITCH_CLIENT_ID }}'
          twitch-client-secret: '${{ secrets.SERVICETESTS_TWITCH_CLIENT_SECRET }}'
          weblate-api-key: '${{ secrets.SERVICETESTS_WEBLATE_API_KEY }}'
          youtube-api-key: '${{ secrets.SERVICETESTS_YOUTUBE_API_KEY }}'

      - name: Service tests (triggered from fork)
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: ./.github/actions/service-tests
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
