name: Package CLI
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'

# Smoke test (render a badge with the CLI) with only the package
# dependencies installed.

jobs:
  test-package-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node: '20'
          - node: '22'
          - node: '24'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Node JS ${{ inputs.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          cd badge-maker
          npm install
          npm link

      - name: Render a badge with the CLI
        run: |
          cd badge-maker
          badge cactus grown :green @flat
