name: Package Library
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'

jobs:
  test-package-lib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node: '20'
            npm: '^10'
            engine-strict: 'false'
          - node: '22'
            npm: '^11'
            engine-strict: 'true'
          - node: '24'
            npm: '^11'
            engine-strict: 'false'
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node }}
          npm-version: ${{ matrix.npm }}
        env:
          NPM_CONFIG_ENGINE_STRICT: ${{ matrix.engine-strict }}

      - name: Package tests
        uses: ./.github/actions/package-tests
