name: Update GitHub API Version
on:
  schedule:
    - cron: '0 7 * * 6'
    # At 07:00 on Saturday
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  update-github-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 16

      - name: Check for new GitHub API version
        run: node scripts/update-github-api.js

      - name: Create Pull Request if config has changed
        uses: peter-evans/create-pull-request@v5
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          commit-message: Update GitHub API Version
          title: Update [GitHub] API Version
          branch-suffix: random
